Public Class NeedModel
    Public Property ID As Long
    Public Property BizUnit As String
    Public Property NeedsID As String
    Public Property CategoryCode As String
    Public Property Country As String
    Public Property State As String
    Public Property District As String
    Public Property Area As String
    Public Property SubArea As String
    Public Property Street As String
    Public Property Postcode As String
    Public Property Building As String
    Public Property Type As String
    Public Property LevelNo As String
    Public Property UnitNo As String
    Public Property Notes As String
    Public Property PreferredDay As String
    Public Property PreferredTimeFrom As TimeSpan?
    Public Property PreferredTimeTo As TimeSpan?
    Public Property CreatedBy As String
    Public Property CreatedAt As Date
    Public Property UpdatedBy As String
    Public Property LastUpdated As Date
    Public Property Status As String
    Public Property ImagePathOne As String
    Public Property ImagePathTwo As String
    Public Property StrPreferredTimeFrom As String
    Public Property StrPreferredTimeTo As String
    Public Property CategoryDescription As String
    Public Property MemberMerchantName As String
End Class

Public Class NeedPostModel
    Public Property ID As Long
    Public Property BizUnit As String
    Public Property NeedsID As String
    Public Property CategoryCode As String
    Public Property Country As String
    Public Property State As String
    Public Property District As String
    Public Property Area As String
    Public Property SubArea As String
    Public Property Street As String
    Public Property Postcode As String
    Public Property Building As String
    Public Property Type As String
    Public Property LevelNo As String
    Public Property UnitNo As String
    Public Property Notes As String
    Public Property PreferredDay As String
    Public Property PreferredTimeFrom As TimeSpan?
    Public Property PreferredTimeTo As TimeSpan?
    Public Property CreatedBy As String
    Public Property CreatedAt As Date
    Public Property UpdatedBy As String
    Public Property LastUpdated As Date
    Public Property Status As String
    Public Property ImagePathOne As String
    Public Property ImagePathTwo As String
End Class
